name: Create Mirror PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Source PR Number'
        required: true

env:
    pr_number: ${{ inputs.pr_number }}
    pr_source_branch: "current"
    pr_target_branch: "current"
    GH_TOKEN: ${{ secrets.PAT }}

jobs:
  Create-PR:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        contents: write

    steps:

    - name: Get mirror repos
      run: |
        repo_name=$(echo ${{ github.repository }} | cut -d'/' -f2)
        echo "pr_source_repo=vyos/${repo_name}" >> $GITHUB_ENV
        echo "pr_target_repo=vyos-networks/${repo_name}" >> $GITHUB_ENV

    - name: Checkout source
      uses: actions/checkout@v4
      with:
        repository: ${{ env.pr_source_repo }}
        ref: ${{ env.pr_source_branch }}
        path: 'source'

    - name: Checkout target
      uses: actions/checkout@v4
      with:
        repository: ${{ env.pr_target_repo }}
        ref: ${{ env.pr_target_branch }}
        persist-credentials: true
        path: 'target'

    - name: Merge setup
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        run_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "WORKFLOW_RUN_URL=${run_url}" >> $GITHUB_ENV

    - name: Create diff patch
      run: |
        cd source
        gh pr diff ${pr_number} > pr-diff-${pr_number}.patch

    - name: Apply diff patch and create PR
      id: apply-changes
      run: |
        source_pr_message=$(gh pr view ${{ env.pr_number }} --repo ${{ env.pr_source_repo }} --json body -q .body)
        cd target
        new_branch_name="mirror/bp/${pr_target_branch}/${pr_number}"
        git checkout -b ${new_branch_name}
        git stash
        git apply --index ../source/pr-diff-${pr_number}.patch
        git commit -m "${source_pr_message} (mirrored PR ${pr_number})"
        git push origin ${new_branch_name}
        gh pr create --base "${{ env.pr_target_branch }}" --head "$new_branch_name" --title "${source_pr_message} (mirror ${{ env.pr_number }})" --body "${source_pr_message}\n\n**Note**: This pull request is mirrored from [${{ env.pr_number }}](https://github.com/${{ env.pr_source_repo }}/pull/${{ env.pr_number }}) using [workflow run](${{ env.WORKFLOW_RUN_URL }})."
